### ISSUE TITLE
Commander broken with nestjs v8

### ISSUE THREAD

**Issue by uvera** [jmcdo29/nest-commander#1154]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

3.13.0 -> 3.14.0

### Describe the regression

When upgrading to v3.14.0 which merged https://github.com/jmcdo29/nest-commander/commit/3dcba7d6d8af329931d083bdc637fef8f009bd21, I get the following error

```console
(node:465857) UnhandledPromiseRejectionWarning: TypeError: this.metadataScanner.getAllMethodNames is not a function
    at DiscoveryService.classMethodsWithMetaAtKey (/home/dusan/Projects/web-api/node_modules/@golevelup/nestjs-discovery/src/discovery.service.ts:171:33)
```

which is caused by fixing use of deprecated method `scanFromPrototype` https://github.com/golevelup/nestjs/commit/92bf751b126c25ca02f1db4cde18c58b28be1d6e

### Minimum reproduction code

```ts

```

### Expected behavior

Nest-commander should continue working with older nest versions.
Minor version upgrade is not expected to introduce breaking changes.

**Comment by micalevisk** [comment]
yeah, indeed

From `@golevelup/nestjs-discovery` this is expected because of their peer deps:

![image](https://github.com/user-attachments/assets/6fcd02aa-7e9e-4c40-9034-d4b41bda4043)

while `nest-commander@3` is supposed to support nestjs v8:

![image](https://github.com/user-attachments/assets/2899902b-db5d-4596-8107-bdabd6f354cf)

So I guess the only fix to this is doing some patching here because there is no version of `@golevelup/nestjs-discovery` that supports both nestjs v8 and v10 at same time, I just checked
